controllers:
    resource: ../src/Controller/
    type: attribute

app_home:
  path: /home
  controller: App\Controller\HomeController::index

# app_article:
#   path: /articles
#   controller: App\Controller\ArticleController::allArticles
